### ISSUE TITLE
Missing store and component-store directories from 2.1.0

### ISSUE THREAD

**Issue by yevit** [timdeschryver/ngrx-immer#20]
Hi,

I've just updated to 2.1.0 and the `store` and `component-store` folders seem to be missing

Heres 2.0.1
![image](https://github.com/timdeschryver/ngrx-immer/assets/2155908/9b6bc5f4-7cdd-4e00-a10b-03bbbb8974a9)

and here 2.1.0
![image](https://github.com/timdeschryver/ngrx-immer/assets/2155908/e3bbb24b-6077-4551-9b3a-39afae7819a6)

as a result I can't import the store, for example:
![image](https://github.com/timdeschryver/ngrx-immer/assets/2155908/37a19b17-502f-4112-a167-b25f8a1548cd)

I'm guessing the build update has caused this? I don't think its related to the PR I've just done but let me know if it is 😕!

**Comment by timdeschryver** [comment]
Hi, thanks for letting me now.
The root cause was the upgrade to Angular 16 (which included changing to secondary entry points).
v2.2.1 (https://github.com/timdeschryver/ngrx-immer/releases/tag/v2.1.1) should fix this.
Could you keep me updated if it works please ? (I'm currently not working on a project that's using this package)

**Comment by yevit** [comment]
I can confirm that v2.2.1 has fixed the issue. Thanks

**Comment by timdeschryver** [comment]
Thanks @yevit !
